Repository baedal-project/baedal, pull requests merged in 2022-11, with the labels that each got.

#6 Docs : Docs 템플릿 추가
  .github/ISSUE_TEMPLATE/📜-docs.md
Labels: 📜 문서

#5 Docs : 커밋 템플릿 작성
  .gitmessage.txt
Labels: 📜 문서

#10 fix : Delete application.properties
  src/main/resources/application.properties
Labels: 🐞 버그

#9 Feat/member
  src/main/java/com/example/baedal/controller/MemberController.java
  src/main/java/com/example/baedal/domain/Member.java
  src/main/java/com/example/baedal/domain/Timestamped.java
  src/main/java/com/example/baedal/dto/request/MemberRequestDto.java
  src/main/java/com/example/baedal/dto/response/MemberResponseDto.java
  src/main/java/com/example/baedal/dto/response/ResponseDto.java
  src/main/java/com/example/baedal/repository/MemberRepository.java
  src/main/java/com/example/baedal/service/MemberService.java
Labels: 💡 기능

#11 Feat/store
  src/main/java/com/example/baedal/controller/StoreController.java
  src/main/java/com/example/baedal/domain/Store.java
  src/main/java/com/example/baedal/repository/StoreRepository.java
  src/main/java/com/example/baedal/service/StoreService.java
  src/main/java/com/example/baedal/shared/Category.java
Labels: 💡 기능

#17 feat : 멤버 주소별 음식점 이름 검색 API
  src/main/java/com/example/baedal/controller/SearchController.java
  src/main/java/com/example/baedal/dto/request/SearchRequestDto.java
  src/main/java/com/example/baedal/repository/StoreRepository.java
  src/main/java/com/example/baedal/service/SearchService.java
Labels: 💡 기능

#14 feat : DB 구축 docker-compose.yml 작성
  docker/docker-compose.yml
Labels: 📜 문서, 💡 기능

#23 feat : 자동배포 스크립트 작성
  .github/workflows/deploy.yml
  CD/deploy.sh
  src/main/java/com/example/baedal/config/WebConfig.java
Labels: 💡 기능

#25 docs : README 작성
  README.md
Labels: 📜 문서

#27 fix : Actions에 로그 찍히는 문제 해결
  CD/deploy.sh
Labels: 🐞 버그

#37 feat : Docker 배포 자동화
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  docker/docker-compose.yml
Labels: 💡 기능

#38 fix : 불필요한 테스트 제거
  src/test/java/com/example/baedal/BaedalApplicationTests.java
Labels: 🐞 버그

#39 fix : jsonignore 추가
  src/main/java/com/example/baedal/domain/Store.java
Labels: 🐞 버그

#43 feat : 모니터링 적용
  build.gradle
  docker/docker-compose.yml
  docker/prometheus/prometheus.yml
Labels: 💡 기능

#50 refactor : 예외처리 추가
  src/main/java/com/example/baedal/repository/LikeRepository.java
  src/main/java/com/example/baedal/service/LikeService.java
  src/main/java/com/example/baedal/service/OrderService.java
  src/main/java/com/example/baedal/service/SearchService.java
  src/main/java/com/example/baedal/service/StoreService.java
Labels: 💡 기능
